CREATE DATABASE VENDAS; 

USE VENDAS;
 
 
CREATE SEQUENCE ID_CLIENTE START 1;
CREATE SEQUENCE ID_USUARIO START 1;
CREATE SEQUENCE ID_PRODUTO START 1;
CREATE SEQUENCE ID_PEDIDO START 1;

CREATE TABLE USUARIO
(
    ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(50), 
    SENHA_USUARIO VARCHAR(50),
    STATUS_USUARIO CHAR(1),

    PRIMARY KEY(ID_USUARIO)

);
INSERT INTO USUARIO VALUES (nextval('ID_USUARIO'),'ADMIN', '1234', 'A');

CREATE TABLE CLIENTE
(
    CODCLI  INT NOT NULL, 
    NOME    VARCHAR(40),
    ENDER   VARCHAR(45),
    BAIRRO  VARCHAR(20),
    CIDADE  VARCHAR(20),
    CEP     VARCHAR(9),
    UF      CHAR(2),
    EMAIL   VARCHAR(30),
    FONE    VARCHAR(10),
    CELULAR VARCHAR(10),

    PRIMARY KEY(CODCLI)
);

CREATE TABLE PRODUTO
(
    CODPROD      INT NOT NULL, 
    DESCRICAO    VARCHAR(30),
    PRECO        NUMERIC(10,2),
    QTDE         NUMERIC(10,2),
    DATA_CAD     TIMESTAMP, 
     PRIMARY KEY (CODPROD)
);


CREATE TABLE PEDIDO
(
    CODPED     INT NOT NULL,
    CODCLI     INT,
    DATA       TIMESTAMP, 

    PRIMARY KEY (CODPED),
    FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI)
);

CREATE TABLE ITENS_PED
(
    CODPED  INT, 
    CODPROD INT,
    QTDE    NUMERIC(10,2),

    FOREIGN KEY(CODPED)  REFERENCES PEDIDO(CODPED),
    FOREIGN KEY(CODPROD) REFERENCES PRODUTO(CODPROD)
);