CREATE DATABASE VENDAS; 

USE VENDAS;
 

CREATE TABLE USUARIO
(
    ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(50), 
    SENHA_USUARIO VARCHAR(50),
    STATUS_USUARIO CHAR(1),

    PRIMARY KEY(ID_USUARIO)

);
INSERT INTO USUARIO(NOME_USUARIO, SENHA_USUARIO, STATUS_USUARIO) VALUES ('ADMIN', '1234', 'A');

CREATE TABLE CLIENTES 
(
    CODCLI  INT NOT NULL AUTO_INCREMENT, 
    NOME    VARCHAR(40),
    ENDER   VARCHAR(45),
    BAIRRO  VARCHAR(20),
    CIDADE  VARCHAR(20),
    CEP     VARCHAR(9),
    UF      CHAR(2),
    EMAIL   VARCHAR(30),
    FONE    VARCHAR(10),
    CELULAR VARCHAR(10),

    PRIMARY KEY(CODCLI)
);

CREATE TABLE PRODUTOS
(
    CODPROD      INT NOT NULL AUTO_INCREMENT, 
    DESCRICAO    VARCHAR(30),
    PRECO        NUMERIC(10,2),
    QTDE         NUMERIC(10,2),
    DATA_CAD     DATETIME, 
     PRIMARY KEY (CODPROD)
);


CREATE TABLE PEDIDOS
(
    CODPED     INT NOT NULL AUTO_INCREMENT,
    CODCLI     INT,
    DATA       DATETIME, 

    PRIMARY KEY (CODPED),
    FOREIGN KEY (CODCLI) REFERENCES CLIENTES (CODCLI)
);

CREATE TABLE ITENS_PED
(
    CODPED  INT, 
    CODPROD INT,
    QTDE    NUMERIC(10,2),

    FOREIGN KEY(CODPED)  REFERENCES PEDIDOS(CODPED),
    FOREIGN KEY(CODPROD) REFERENCES PRODUTOS(CODPROD)
);